pipeline {
    agent any
    stages {
        stage('Initialize') {
            steps {
                script {
                    def dockerHome = tool 'docker-latest'
                    env.PATH = "${dockerHome}/bin:${env.PATH}"
                }
                checkout scm
            }
        }
        
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.9.0'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        
        stage('Test') {
            agent {
                docker {
                    image 'maven:3.9.0'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('Deliver') {
            agent {
                docker {
                    image 'maven:3.9.0'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Build Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-repo', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh '/usr/bin/docker build -t maulana48/simple-java-maven-app .'
                    sh "echo $PASS | /usr/bin/docker login -u $USER --password-stdin"
                    sh '/usr/bin/docker push maulana48/simple-java-maven-app'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
	      		    // Create an Approval Button with a timeout of 15minutes.
	                timeout(time: 2, unit: "MINUTES") {
	                    input message: 'Do you want to approve the deployment?', ok: 'Yes'
	                }
			
	                echo "Initiating deployment"

                    def dockerCmd = '/usr/bin/docker run  -p 8080:8080 --name test -d maulana48/simple-java-maven-app:latest && /usr/bin/docker exec test java -jar my-app-1.0-SNAPSHOT.jar'
                    sshagent(['maulana48-ec2']) {
                        sh "ssh -o StrictHostKeyChecking=no ec2-user@18.142.179.80 ${dockerCmd}"
                    }
                }
            }
        }
    }
}
