node {
    stage('Cleanup Workspace') {
        cleanWs()
    }
    stage('Checkout') {
        steps {
            checkout([$class: 'GitSCM', 
                branches: [[name: '*/master']],
                userRemoteConfigs: [[url: '/home/Documents/simple-java-maven-app']]], 
                clean: true)
        }
    }
    stage('Deploy') {
        withAWS(region: 'us-east-1', credentials: 'maulana48') {
            sh 'pwd'
            sh 'ls -la'
            sh 'ssh -o "StrictHostKeyChecking no" -i ./test.pem test@18.142.179.80 "./jenkins/scripts/deliver.sh"'
        }
    }
}
